version: "2"

volumes:
  database:
    driver: local
  
networks:
  proxy-tier:
    driver: bridge

services:
  graphql:
    build: .
    container_name: bam_api-graphql
    restart: unless-stopped
    environment:
      - NODE_ENV=staging
      - VIRTUAL_HOST=bam-api.cloud.bam.tech
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=bam-api.cloud.bam.tech
      - LETSENCRYPT_EMAIL=tychot@bam.tech
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - proxy-tier

  postgres:
    image: postgres:9.6
    container_name: bam_api-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tql
      - POSTGRES_PASSWORD=itstqldude
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - proxy-tier
