
nginx-proxy:
  image: jwilder/nginx-proxy:latest
  ports:
   - "80:80"
   - "443:443"
  volumes:
    - './docker/proxy/certs:/etc/nginx/certs:ro'
    - '/etc/nginx/vhost.d'
    - '/usr/share/nginx/html'
    - '/var/run/docker.sock:/tmp/docker.sock:ro'

letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion:latest
  volumes_from:
    - nginx-proxy
  volumes:
    - './docker/proxy/certs:/etc/nginx/certs:rw'
    - '/var/run/docker.sock:/var/run/docker.sock:ro'

graphql:
  image: quay.io/tychot/tql
  container_name: bam_api-graphql
  restart: unless-stopped
  environment:
    - NODE_ENV=staging
    - VIRTUAL_HOST=bam-api.cloud.bam.tech
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=bam-api.cloud.bam.tech
    - LETSENCRYPT_EMAIL=tychot@bam.tech
  ports:
    - "3000"
  links:
    - postgres

postgres:
  image: postgres:9.6
  container_name: bam_api-postgres
  restart: unless-stopped
  environment:
    - POSTGRES_USER=tql
    - POSTGRES_PASSWORD=itstqldude
  volumes:
    - ./docker/database:/var/lib/postgresql/data
